### ISSUE TITLE
This is going to be my checklist example:

### ISSUE THREAD

**Issue by Anbarasi-A** [Anbarasi-A/markdown-portfolio#2]
This is going to be my checklist example:
 - [X] Add this checklist as a comment to this issue
 - [x] Click on the green `comment` button
 - [x] Don't forget to *celebrate* writing your first bit of Markdown!
 - [x] You can also do a little _Dance_ if you want to.
 - [x] And maybe you can _*celebrate* and dance_

_Originally posted by @Anbarasi-A in https://github.com/Anbarasi-A/markdown-portfolio/issues/1#issuecomment-1069236074_
